// next-auth session status

const USER_SESSION_STATUS_AUTHENTICATED = "authenticated";

const USER_SESSION_STATUS_LOADING = "loading";

const USER_SESSION_STATUS_UNAUTHENTICATED = "unauthenticated";

export const USER_SESSION_STATUS = {
  AUTHENTICATED: USER_SESSION_STATUS_AUTHENTICATED,
  LOADING: USER_SESSION_STATUS_LOADING,
  UNAUTHENTICATED: USER_SESSION_STATUS_UNAUTHENTICATED,
};
